### ISSUE TITLE
Question : free for commercial use?

### ISSUE THREAD

**Issue by belavina** [flanggut/smvs#10]
It looks like SMVS is free from patents / code contamination (and [this](https://github.com/openMVG/awesome_3DReconstruction_list#opensource-mvs-multiple-view-stereovision) table seems to confirm it ). 

Is it safe for commercial use ? Do you happen to know if SMVS uses any GPL parts from MVE?

Thank you

**Comment by flanggut** [comment]
Hi. Yes, SMVS is completely free to use. We also recently removed all GPL contaminated parts from MVE, so everything included in both projects is now solely under the BSD 3 Clause license.

**Comment by belavina** [comment]
Thank you for your quick reply
