### ISSUE TITLE
 A question about Semi-global Matching argument

### ISSUE THREAD

**Issue by youngzi1004** [flanggut/smvs#11]
Hi! In the case that the mve scenes do not contain an initial sparse point cloud, how can we estimation an initial depth sweep. It seems that the argument influences the results a lot in this case. could you give some suggestions?
thanks for your reading.

**Comment by HelliceSaouli** [comment]
use sfmrecon to generate the initial input to smvs

**Comment by flanggut** [comment]
There is no easy way to solve this problem as it completely depends on your camera parameters and the scene you're trying to reconstruct. If you don't have any a priori information you can't do much better than trial and error.

**Comment by flanggut** [comment]
No further activity so I am closing this.
