### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by wxyz-lang** [flanggut/smvs#12]
Hi, your paper and project is the best work i have met on the 3D reconstruction field.

I have two questions about the code:
1.what the option " -S (Shading-based optimization)" means? It's not using geometric energy term and only using shading energy term?
2.I only want to use the geometric energy term to optimize my depthmap  ,but i can't find where to change the code in the functions of gauss_newton_step.cc, can you give me some advice?

**Comment by flanggut** [comment]
`-S` activates the shading term as described in the README. Without `-S` you will have the geometric energy only.
