### ISSUE TITLE
an issue in win10 system

### ISSUE THREAD

**Issue by youngzi1004** [flanggut/smvs#13]
hi! thanks for your hard working. I have successfully compiled SMVS in Windows 10 + VisualStudio 2013. However, the caculated point cloud in win10 isn't as accurate as that in macOS.  The complete pipelines are the same in different systems. The results for dataset:
 http://vision.middlebury.edu/mview/data/

win10+vs2013:
![image](https://user-images.githubusercontent.com/29294740/27332792-fc0a9ffc-55f5-11e7-9075-f20ac57b279b.png)

macOS:
![image](https://user-images.githubusercontent.com/29294740/27332835-29586aca-55f6-11e7-8254-d5a60e44d328.png)

could you give some advices? 

thanks very much!

**Comment by flanggut** [comment]
Sorry, I have no idea. From my perspective there should be no difference between the different OSs but I haven't worked with windows in years so I cannot really help you.
