### ISSUE TITLE
Strecha dataset

### ISSUE THREAD

**Issue by HelliceSaouli** [flanggut/smvs#15]
Hello 
Well, it seems that Strecha dataset (fountain P11) has been removed from the original web site.
i wonder if you know why and if you can upload it or where can i find it

**Comment by pmoulon** [comment]
You can find it here https://github.com/openMVG/SfM_quality_evaluation/tree/master/Benchmarking_Camera_Calibration_2008

**Comment by HelliceSaouli** [comment]
@pmoulon  thank you, soo much sir.
I intend to use this data in my research paper is it allowed (since it is no longer open source in the original web page)? and what paper of yours should i cite.

**Comment by pmoulon** [comment]
Since the initial website is down. I suppose you can cite the original Strecha paper and the image repository as a link.

**Comment by flanggut** [comment]
Thanks @pmoulon !
