### ISSUE TITLE
Middelburry dataset

### ISSUE THREAD

**Issue by HelliceSaouli** [flanggut/smvs#17]
Hello
I was wondering how did you handle the Middelburry ground truth dataset for evaluation. I mean because smvs is based on _sfmrecon_ which give ambiguous parameters (correct but not identical to ground truth) thus leading the reconstruction to be out bounding box given by the website aka the reconstruction is not in the true scene coordinate system. I spoke to Mr Simon in issue [388](https://github.com/simonfuhrmann/mve/issues/388) the solution he proposes is kind hard ( and not worth it since I need to do it for just one time for evaluation ). How did you tackled this problem
Thanks

**Comment by flanggut** [comment]
We addressed this issue in MVE. See https://github.com/simonfuhrmann/mve/wiki/Middlebury-Datasets
