### ISSUE TITLE
What is the difference between simplify option and MeshSimplifier class?

### ISSUE THREAD

**Issue by s-wtnb** [flanggut/smvs#20]
What is the difference between simplify option in smvs and MeshSimplifier class?
preprocessing or postprocessing only?

thanks.

**Comment by flanggut** [comment]
This is just post processing as it only effects how the final depth maps are combined into a point cloud. I added this so you can "comfortably" preview large reconstructions before you process them with an actual surface reconstruction algorithm. For large datasets the pointclouds can get quite big, and smaller graphics cards might struggle.

**Comment by s-wtnb** [comment]
thx!!
