### ISSUE TITLE
Is there a way to make it more right height  like dmrecon?

### ISSUE THREAD

**Issue by s-wtnb** [flanggut/smvs#28]
hi.
I make 3D data with openMVG + (SMVS or dmrecon) + PoissonRecon.
Using SMVS, I'm satisfied with finishing the looks beautifully. On the other hand, the actual position is expressed smoothly.

Please see the figure below.
This is a sectional view of 3D cut vertically.
![ws000120](https://user-images.githubusercontent.com/25291845/41964465-03d2a662-7a35-11e8-9ed0-a7ae153e8b94.JPG)

The actual value black acquired by laser, red is dmrecon, blue is SMVS.
SMVS is a smooth line.
Is there a way to get closer to reality by changing settings and code?

**Comment by flanggut** [comment]
If you want the highest possible detail you should use the `-o1` option to optimize on the finest scale. If that is not enough you can change the stopping criteria for the optimization by setting the value [here](https://github.com/flanggut/smvs/blob/master/lib/depth_optimizer.cc#L296) to something smaller like `0.05` - I should actually make this parameter adaptive depending on the scale.

**Comment by s-wtnb** [comment]
thx!
I will try it.
