### ISSUE TITLE
Models are flipped over X axis

### ISSUE THREAD

**Issue by mordka** [flanggut/smvs#30]
First of all, I would like to thank you for this amazing tool. I'm using drone videos for scene reconstruction and it works amazingly well. Extracted video framwes are fed to the MVE pipeline. Standard parameters are used to reconstruct the scene. Here is an example of `meta.ini` rotation parameter generated:
```rotation = -0.9634011388 -0.2680799067 -0.001736412523 0.1153697371 -0.4203992188 0.900010407 -0.2420091629 0.8668632507 0.4359418452```
Then `smvsrecon` is run on a prepared scene folder. 
All goes fine, the resulting point cloud looks correct, however it's **always** rotated (for every different set of images, even for sample temple model) as on the screenshots. I'm not sure if this is wrong on SfM step or it's smvs recon not picking up camera orientation properly.
This causes problems in the next steps - mesh generation and texture appliance. The resulting models are black and rotated. 
One possible workaround is to take ply file and rotate it programatically using `meshlabserver` filter. 

![image](https://user-images.githubusercontent.com/3659502/42439731-f6e495c2-8363-11e8-97d5-5ade4a2fd4e0.png)

Manually rotated 180 degrees over X axis and barycenter point - looks fine
![image](https://user-images.githubusercontent.com/3659502/42439779-13a7538e-8364-11e8-8e30-d0264e8682ea.png)

**Comment by flanggut** [comment]
Hi! I am not sure what you're referring to exactly. The global rotation of the scene is basically arbitrary as we cannot infer it only from the input images. This should however not have an effect on the overall pipeline. 

If you just want to flip the mesh for the output you can add something like
```
#include "mve/mesh_tools.h"
...
        math::Matrix3f flip;
        flip.fill(0.f);
        flip(0, 0) = 1.f;
        flip(1, 1) = -1.f;
        flip(2, 2) = -1.f;
        mve::geom::mesh_transform(mesh, flip);
...
```
to SMVS (for example [here](https://github.com/flanggut/smvs/blob/master/app/smvsrecon.cc#L336)).

**Comment by mordka** [comment]
Thanks @flanggut , that change does the job, resulting ply file is flipped now. However it caused segfaults during next step - texturing using texrecon. So the best thing for me to do now, is to debug MVE orientation parameters.

**Comment by flanggut** [comment]
If you want to texture the model as well you should flip it after the texturing, otherwise it is in the wrong coordinate system.
