### ISSUE TITLE
Dense reconstruction with Blender cameras

### ISSUE THREAD

**Issue by donlk** [flanggut/smvs#35]
Hi,
I've posted this issue on the [MVE issue tracker](https://github.com/simonfuhrmann/mve/issues/492) as well, but i'm posting this here too, as SMVS plays a key part in what i'm doing.
I've set up a scene in Blender with an object at the origin and a camera to rotate around it. I've rendered out several frames while rotating the camera around 10 degrees, and exported the camera positions from Blender using [this script](https://blender.stackexchange.com/questions/38009/3x4-camera-matrix-from-blender-camera). I've set up an MVE scene based on the rendered frames and the exported cameras and i'm trying to reconstruct it using SMVS (in this case without any SFM points obviously).
The problem is, MVE puts out either an empty point cloud every time or a one with weirdly placed points. I suspect the issue might be in the camera conversion. I'm not sure what coordinate system MVE is using, what rotation and translation matrices it expects.
Maybe you can help me with what i'm doing wrong.

**Comment by flanggut** [comment]
Resolved in MVE issue.
