### ISSUE TITLE
occurred "Illegal instruction (core dumped)"  when   smvsrecon <scene-dir>

### ISSUE THREAD

**Issue by wxyz-lang** [flanggut/smvs#4]
Shading-aware Multi-view Stereo (built on Dec 22 2016, 15:17:43)

Initializing scene with 6 views...
Initialized 6 views (max ID is 5), took 27ms.
Reading Photosynther file (6 cameras, 221 features)...
Automatic input scale: 2
Input embedding: undist-L2
Output embedding: smvs-B2
Starting 1/6 ID: 0 Neighbors: 3 2 5 
Starting 2/6 ID: 1 Neighbors: 5 4 2 

Illegal instruction (core dumped)

**Comment by flanggut** [comment]
This is strange. I am not sure what could cause this error. Would you be able to send me your MVE scene folder so I can have a closer look at what happens during execution?

**Comment by wxyz-lang** [comment]
I have changed another computer ,it's ok!
