### ISSUE TITLE
illumination model

### ISSUE THREAD

**Issue by HelliceSaouli** [flanggut/smvs#7]
Hello 
your work is so amazing one of the best paper i read.
so i have some ideas and i wanted to test them as the title says, i want to change the illumination model tweak it here and there and see what i got, he thing is i can't find where you did put the illumination model, and the shading opitimization  term, i know it's somewhere inside depthoptimzer but i'm being lasy and i would like you to point me exactly to the right direction

thanks
best regards

**Comment by flanggut** [comment]
Hi, depending on what you're aiming for you should start with [this function](https://github.com/flanggut/smvs/blob/master/lib/gauss_newton_step.cc#L34). It directly builds the linear Gauss-Newton step, so you have to make sure that you construct the matrix entries correctly.

**Comment by HelliceSaouli** [comment]
Well am Phd student, and  you mentioned paper [1] (epic work really) that ur lighting model is kind of weak, and for this am designing new model. my objectify generally speaking is get rid of the lambertian assumption in computer vision algorithm specially stereo. so i'm open to any suggestion

Note that your paper has being suggested to me by Mr  Michael Goesele after a brief conversation via emails
thank you for your replies
best regards
