### ISSUE TITLE
cxxflags not adequate when building wiht gcc7

### ISSUE THREAD

**Issue by bartoszek** [flanggut/smvs#9]
When building on archlinux with gcc7(7.1.1) compiler complains about `target specific option mismatch`. Boosting -msse from 4.1 to 4.2 fixes the issue 
gcc output:
>g++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -pthread -I../../mve-git/libs -I../lib -msse4.1 -pthread -D_FORTIFY_SOURCE=2 -c -o bicubic_patch.o bicubic_patch.cc
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/include/smmintrin.h:811:0,
                 from sgm_stereo.cc:11:
/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/include/popcntintrin.h: In member function ‘void smvs::SGMStereo::create_cost_volume(float, float, int)’:
/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/include/popcntintrin.h:42:1: error: inlining failed in call to always_inline ‘long long int _mm_popcnt_u64(long long unsigned int)’: target specific option
mismatch

**Comment by flanggut** [comment]
Fixed in 2053d3f8c989f4d636865e12ad217c3bf673ccfc
